# Project metadata
name: wallet_comparison
description: "A new Flutter project."

# Version number format: version: <major>.<minor>.<patch>+<build>
# The +<build> number is used for Android/iOS versioning
version: 1.0.0+1

# SDK version constraint
environment:
  sdk: ^3.5.0  # Requires Dart SDK 3.5.0 or higher

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  # Data grid for displaying wallet comparison data
  syncfusion_flutter_datagrid: ^26.2.14
  # For creating gradient backgrounds and text
  flutter_gradient_colors: ^2.1.1
  # For custom typography
  google_fonts: ^6.2.1
  # For opening external links (e.g., wallet websites)
  url_launcher: ^6.0.17
  # For rendering SVG images (e.g., wallet logos)
  flutter_svg: ^1.0.3
  # iOS-style icons
  cupertino_icons: ^1.0.8
  # Firebase integration
  firebase_core: ^3.5.0
  # Firebase Cloud Functions
  cloud_functions: ^5.1.2

# Development dependencies (not included in production builds)
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linting rules for code quality
  flutter_lints: ^4.0.0

# Flutter-specific configuration
flutter:
  # Enables Material Design widgets
  uses-material-design: true

  # Asset files (images, fonts, etc.)
  assets:
    - assets/  # All files in the assets directory

