const List<String> categories = [
  'Wallet',
  'Icon',
  'Score',
  'Android',
  'APK',
  'IOS',
  'Windows',
  'MacOS',
  'Linux',
  'Available in USA',
  'Dark Mode',
  'Multiple Languages',
  'BTC Only',
  'Self-Custody',
  'Open-Source',
  'No KYC',
  'Own Node',
  'Tor',
  'MFA',
  'Encrypted Backup',
  'Plausible Deniability',
  'Inheritance',
  'On-Chain',
  'BIP-39 Passphrase',
  'Paynym',
  'Multiple Wallets',
  'Watch Only',
  'Multisig',
  'Hardware Wallet Support',
  'Coin Control',
  'UTXO Labels',
  'NFC',
  'Silent Payments',
  'Stonewall',
  'Payjoin',
  'PSBT',
  'RBF',
  'CPFP',
  'Taproot',
  'Batch TXs',
  'Show X(Z)pub',
  'Lightning Network',
  'Zaps',
  'LNURL',
  'Bolt 12',
  'Multiple Mints',
  'Multiple LSPs',
  'Fedimint',
  'Cashu',
  'Liquid',
  'USDT',
  'Trampoline Routing',
  'Nostr',
  'Contact Book',
  'BTC Over Email',
  'Point of Sale',
  'Unified QR',
  'Sign Message',
  'Testnet',
  'Signet',
  'Buy',
  'Sell',
  'Shop',
  'Swaps',
  'Atomic Swaps',
];

const List<String> filters = [
  'Android',
  'APK',
  'IOS',
  'Windows',
  'MacOS',
  'Linux',
  'Available in USA',
  'Dark Mode',
  'Multiple Languages',
  'BTC Only',
  'Self-Custody',
  'Open-Source',
  'No KYC',
  'Own Node',
  'Tor',
  'MFA',
  'Encrypted Backup',
  'Plausible Deniability',
  'Inheritance',
  'On-Chain',
  'BIP-39 Passphrase',
  'Paynym',
  'Multiple Wallets',
  'Watch Only',
  'Multisig',
  'Hardware Wallet Support',
  'Coin Control',
  'UTXO Labels',
  'NFC',
  'Silent Payments',
  'Stonewall',
  'Payjoin',
  'PSBT',
  'RBF',
  'CPFP',
  'Taproot',
  'Batch TXs',
  'Show X(Z)pub',
  'Lightning Network',
  'Zaps',
  'LNURL',
  'Bolt 12',
  'Multiple Mints',
  'Multiple LSPs',
  'Fedimint',
  'Cashu',
  'Liquid',
  'USDT',
  'Trampoline Routing',
  'Nostr',
  'Contact Book',
  'BTC Over Email',
  'Point of Sale',
  'Unified QR',
  'Sign Message',
  'Testnet',
  'Signet',
  'Buy',
  'Sell',
  'Shop',
  'Swaps',
  'Atomic Swaps',
];
